package web

type UI struct{}

func NewUI() *UI { return &UI{} }

func (u *UI) Render() string {
	return `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Zapatos ERP</title>
<style>
body{font-family:system-ui,sans-serif;background:#0e1116;color:#f4efe7;margin:0;padding:24px}input,button,textarea,select{font:inherit}input,textarea,select{background:#111821;color:#f4efe7;border:1px solid #334;padding:8px;border-radius:8px}button{background:#d8b88a;color:#1b1209;border:0;padding:8px 12px;border-radius:8px;cursor:pointer}.row{display:flex;gap:8px;flex-wrap:wrap}.card{border:1px solid #334;border-radius:14px;padding:16px;margin:12px 0;background:#131821}.muted{color:#a6adbb}.hidden{display:none}.pill{display:inline-block;padding:4px 8px;border:1px solid #334;border-radius:999px;margin-right:6px}.table{width:100%;border-collapse:collapse}.table th,.table td{border-bottom:1px solid #334;padding:6px;text-align:left;vertical-align:top}.stack{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:8px}</style></head><body>
<h1>Zapatos ERP</h1><p class="muted">ERP administrativo para fábrica de zapatos.</p>
<div id="login" class="card"><h2>Ingresar</h2><div class="row"><input id="username" placeholder="usuario"><input id="password" type="password" placeholder="contraseña"><button onclick="login()">Entrar</button></div><p class="muted">admin/admin123, warehouse/warehouse123, sales/sales123, accounting/accounting123, audit/audit123, production/production123</p></div>
<div id="app" class="hidden"><div class="card"><div class="row"><button onclick="refreshAll()">Refrescar</button><button onclick="logout()">Salir</button><span id="me" class="muted"></span></div></div><div id="sections"></div></div>
<script>
const LS='zapatos-erp-token';
const ROLES={administrador:['raw-materials','finished-goods','packaging','logistics','billing','foxpro','audit'],almacen:['raw-materials','finished-goods','packaging','logistics'],produccion:['raw-materials','finished-goods','packaging','logistics'],ventas:['finished-goods','billing'],contabilidad:['billing'],auditoria:['raw-materials','finished-goods','packaging','logistics','billing','audit']};
async function api(path, opts={}){opts.headers=opts.headers||{};opts.headers['Content-Type']='application/json';const token=localStorage.getItem(LS);if(token)opts.headers['Authorization']='Bearer '+token;const res=await fetch(path,opts);const text=await res.text();let data;try{data=text?JSON.parse(text):null}catch{data=text}if(!res.ok)throw new Error((data&&data.error)||res.statusText);return data}
async function login(){const data=await api('/api/login',{method:'POST',body:JSON.stringify({username:username.value,password:password.value})});localStorage.setItem(LS,data.token);await start()}
function logout(){localStorage.removeItem(LS);location.reload()}
let activeSections=[];
async function start(){const me=await api('/api/me');document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('me').textContent=me.username+' · '+me.role;activeSections=ROLES[me.role]||[];render();}
function render(){document.getElementById('sections').innerHTML=activeSections.map(id=>'<div class="card"><h2>'+titleFor(id)+'</h2><div id="'+id+'"></div></div>').join('');refreshAll()}
function titleFor(id){return {'raw-materials':'Materia prima','finished-goods':'Producto terminado','packaging':'Embalaje / transporte','logistics':'Stock y logística','billing':'Facturación','foxpro':'Integración FoxPro','audit':'Auditoría'}[id]||id}
async function refreshAll(){for(const id of activeSections){await ({'raw-materials':refreshRaw,'finished-goods':refreshFinished,'packaging':refreshPackaging,'logistics':refreshLogistics,'billing':refreshBilling,'foxpro':refreshFoxpro,'audit':refreshAudit}[id]||(()=>Promise.resolve()))()}}
async function refreshRaw(){if(!activeSections.includes('raw-materials')) return;const items=await api('/api/raw-materials');document.getElementById('raw-materials').innerHTML=formRaw()+table(items,['id','name','unit','minStock','dimensions'])}
async function refreshFinished(){if(!activeSections.includes('finished-goods')) return;const items=await api('/api/finished-goods');document.getElementById('finished-goods').innerHTML=formFinished()+formAdjust()+table(items,['id','style','size','color','stock','dimensions'])}
async function refreshPackaging(){if(!activeSections.includes('packaging')) return;const items=await api('/api/packaging');document.getElementById('packaging').innerHTML=formPackaging()+table(items,['id','name','transportMode','maxUnits','dimensions'])}
async function refreshLogistics(){if(!activeSections.includes('logistics')) return;const items=await api('/api/logistics');document.getElementById('logistics').innerHTML=formLogistics()+table(items,['id','name','zone','capacityUnits','dimensions'])}
async function refreshBilling(){if(!activeSections.includes('billing')) return;const items=await api('/api/invoices');document.getElementById('billing').innerHTML=formInvoice()+formIssue()+table(items,['id','customerId','total','tax','status'])}
async function refreshFoxpro(){if(!activeSections.includes('foxpro')) return;const item=await api('/api/foxpro');document.getElementById('foxpro').innerHTML='<div class="row"><button onclick="syncFoxpro()">Sincronizar</button></div><pre>'+escapeHtml(JSON.stringify(item,null,2))+'</pre>'}
async function refreshAudit(){if(!activeSections.includes('audit')) return;const items=await api('/api/audit');document.getElementById('audit').innerHTML='<div class="row"><a class="pill" href="/api/audit/export" target="_blank">Exportar CSV</a></div>'+table(items,['at','actor','action','entity'])}
function formRaw(){return '<form class="row" onsubmit="event.preventDefault();saveRaw(this)"><input name="id" placeholder="id"><input name="name" placeholder="nombre"><input name="unit" placeholder="unidad"><input name="minStock" type="number" placeholder="mínimo"><button>Guardar</button></form>'}
function formFinished(){return '<form class="row" onsubmit="event.preventDefault();saveFinished(this)"><input name="id" placeholder="id"><input name="style" placeholder="estilo"><input name="size" placeholder="talle"><input name="color" placeholder="color"><input name="stock" type="number" placeholder="stock"><div class="stack"><input name="lengthCm" type="number" step="0.01" min="0.01" placeholder="largo cm"><input name="widthCm" type="number" step="0.01" min="0.01" placeholder="ancho cm"><input name="heightCm" type="number" step="0.01" min="0.01" placeholder="alto cm"><input name="weightKg" type="number" step="0.01" min="0" placeholder="peso kg"></div><button>Guardar</button></form>'}
function formAdjust(){return '<form class="row" onsubmit="event.preventDefault();adjustFinished(this)"><input name="id" placeholder="id"><input name="delta" type="number" placeholder="delta"><input name="note" placeholder="nota"><button>Ajustar stock</button></form>'}
function formPackaging(){return '<form class="row" onsubmit="event.preventDefault();savePackaging(this)"><input name="id" placeholder="id"><input name="name" placeholder="nombre"><input name="transportMode" placeholder="transporte"><input name="maxUnits" type="number" min="1" placeholder="unidades"><div class="stack"><input name="lengthCm" type="number" step="0.01" min="0.01" placeholder="largo cm"><input name="widthCm" type="number" step="0.01" min="0.01" placeholder="ancho cm"><input name="heightCm" type="number" step="0.01" min="0.01" placeholder="alto cm"><input name="weightKg" type="number" step="0.01" min="0" placeholder="peso kg"></div><button>Guardar</button></form>'}
function formLogistics(){return '<form class="row" onsubmit="event.preventDefault();saveLogistics(this)"><input name="id" placeholder="id"><input name="name" placeholder="nombre"><input name="zone" placeholder="zona"><input name="capacityUnits" type="number" min="1" placeholder="capacidad"><div class="stack"><input name="lengthCm" type="number" step="0.01" min="0.01" placeholder="largo cm"><input name="widthCm" type="number" step="0.01" min="0.01" placeholder="ancho cm"><input name="heightCm" type="number" step="0.01" min="0.01" placeholder="alto cm"><input name="weightKg" type="number" step="0.01" min="0" placeholder="peso kg"></div><button>Guardar</button></form>'}
function formInvoice(){return '<form class="row" onsubmit="event.preventDefault();saveInvoice(this)"><input name="id" placeholder="id"><input name="customerId" placeholder="cliente"><input name="total" type="number" step="0.01" placeholder="total"><input name="tax" type="number" step="0.01" placeholder="impuesto"><select name="status"><option>draft</option><option>issued</option><option>paid</option><option>void</option></select><button>Guardar</button></form>'}
function formIssue(){return '<form class="row" onsubmit="event.preventDefault();issueInvoice(this)"><input name="id" placeholder="id"><button>Emitir</button></form>'}
function table(items, cols){return '<table class="table"><thead><tr>'+cols.map(c=>'<th>'+c+'</th>').join('')+'</tr></thead><tbody>'+items.map(item=>'<tr>'+cols.map(c=>'<td>'+escapeHtml(formatValue(item[c]))+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
function formatValue(value){if(value&&typeof value==='object'&&'lengthCm' in value&&'widthCm' in value&&'heightCm' in value){return 'L '+value.lengthCm+' × A '+value.widthCm+' × H '+value.heightCm+' cm / '+(value.weightKg??0)+' kg'}return value??''}
function escapeHtml(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function dimensionsFrom(form){return {lengthCm:Number(form.lengthCm.value),widthCm:Number(form.widthCm.value),heightCm:Number(form.heightCm.value),weightKg:Number(form.weightKg.value)}}
async function saveRaw(form){await api('/api/raw-materials',{method:'POST',body:JSON.stringify({id:form.id.value,name:form.name.value,unit:form.unit.value,minStock:Number(form.minStock.value),dimensions:dimensionsFrom(form)})});await refreshRaw()}
async function saveFinished(form){await api('/api/finished-goods',{method:'POST',body:JSON.stringify({id:form.id.value,style:form.style.value,size:form.size.value,color:form.color.value,stock:Number(form.stock.value),dimensions:dimensionsFrom(form)})});await refreshFinished()}
async function adjustFinished(form){await api('/api/finished-goods/'+encodeURIComponent(form.id.value),{method:'PATCH',body:JSON.stringify({delta:Number(form.delta.value),note:form.note.value})});await refreshFinished()}
async function savePackaging(form){await api('/api/packaging',{method:'POST',body:JSON.stringify({id:form.id.value,name:form.name.value,transportMode:form.transportMode.value,maxUnits:Number(form.maxUnits.value),dimensions:dimensionsFrom(form)})});await refreshPackaging()}
async function saveLogistics(form){await api('/api/logistics',{method:'POST',body:JSON.stringify({id:form.id.value,name:form.name.value,zone:form.zone.value,capacityUnits:Number(form.capacityUnits.value),dimensions:dimensionsFrom(form)})});await refreshLogistics()}
async function saveInvoice(form){await api('/api/invoices',{method:'POST',body:JSON.stringify({id:form.id.value,customerId:form.customerId.value,total:Number(form.total.value),tax:Number(form.tax.value),status:form.status.value})});await refreshBilling()}
async function issueInvoice(form){await api('/api/invoices/'+encodeURIComponent(form.id.value)+'/issue',{method:'POST'});await refreshBilling()}
async function syncFoxpro(){await api('/api/foxpro/sync',{method:'POST'});await refreshFoxpro()}
if(localStorage.getItem(LS)){start().catch(()=>{})}
</script></body></html>`
}

